- name: Install tailscale on server
  hosts: development
  roles:
    - role: artis3n.tailscale
      vars:
        # Example pulling the API key from the env vars on the host running Ansible
        # tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_authkey: "{{ TAILSCALE_KEY }}"

# https://github.com/artis3n/ansible-role-tailscale
