services:
  plex:
    image: lscr.io/linuxserver/plex:1.41.1.9057-af5eaea7a-ls241
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /home/daniel/Documents/Docker/plex:/config
      - /home/daniel/Videos/tv:/tv
      - /home/daniel/Videos/movies:/movies
      - /mnt/zurg/movies:/zurg/movies
      - /mnt/zurg/shows:/zurg/series
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.plex.rule=Host(`plex.zorab.im`)"
     - "traefik.http.routers.plex.entrypoints=websecure"
     - "traefik.http.routers.plex.tls.domains[0].main=zorab.im"
     - "traefik.http.routers.plex.tls.domains[0].sans=*.zorab.im"
     - "traefik.http.routers.plex.tls.certResolver=cloudflare"
     - "traefik.http.services.plex.loadbalancer.server.port=32400"      
    restart: unless-stopped