name: etcd
services:
  etcd:
    ports:
      - 2379:2379
      - 2380:2380
    container_name: etcd
    restart: always
    # image: quay.io/coreos/etcd:v3.5.0
    image: ${REGISTRY}:v3.5.0
    command: >
      /usr/local/bin/etcd
      --data-dir=/etcd-data
      --name node1
      --initial-advertise-peer-urls http://${NODE1}:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://${NODE1}:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster node1=http://${NODE1}:2380
