version: '3.0'

services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:2.20.0
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Europe/Isle_of_Man'
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped