---
- name: Deploy Docker Compose application
  hosts: docker
  become: true
  vars:
    app_name: komodo
    app_directory: /docker/{{ app_name }}

  tasks:

    - name: Ensure the app directory exists
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory
        mode: '0755'  # Optional: Set directory permissions

    - name: Copy Docker Compose file to target machine
      ansible.builtin.copy:
        src: compose.agent.yml
        dest: "{{ app_directory }}/compose.yml"

    - name: Copy environment file to target machine
      ansible.builtin.copy:
        src: .env
        dest: "{{ app_directory }}/compose.env"

    - name: Ensure the app directory is the working directory
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory

    - name: Run Docker Compose
      ansible.builtin.command: docker compose up -d
      args:
        chdir: "{{ app_directory }}"
