---
- name: Create a volume
  community.docker.docker_volume:
    name: portainer_data

- name: Copy Docker Compose files
  ansible.builtin.copy:
    src: files/docker-compose.yml
    dest: "{{ portainer_dir }}"

- name: Restart services
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_dir }}"
    state: absent

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_dir }}"
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
