---
- name: Install ceph common tools
  hosts: docker
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ceph-common

    - name: Create /etc/ceph/ceph.client.vmuser.keyring with the vault value
      ansible.builtin.copy:
        content: "{{ vault_ceph_password }}"
        dest: /etc/ceph/ceph.client.vmuser.keyring
        owner: root
        group: root
        mode: '0644'
