version: "3.2"
services:
  backrest:
    image: garethgeorge/backrest:v0.17.1-scratch
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - /backup:/userdata # mount your directories to backup somewhere in the filesystem
      - /MY-REPOS:/repos # (optional) mount your restic repositories somewhere in the filesystem.
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
    restart: unless-stopped
    ports:
      - 9898:9898
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.backrest.rule=Host(`backrest.zorab.im`)"
     - "traefik.http.routers.backrest.entrypoints=websecure"
     - "traefik.http.routers.backrest.tls.domains[0].main=zorab.im"
     - "traefik.http.routers.backrest.tls.domains[0].sans=*.zorab.im"
     - "traefik.http.routers.backrest.tls.certResolver=cloudflare"
     #- "traefik.http.services.backrest.loadbalancer.server.port=9898"  
     - "traefik.http.services.backrest.loadbalancer.server.url=http://dockerhost01.server:9898"

    networks:
      - traefik_public      
 
networks:
  traefik_public:
    external: true           