services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    container_name: orbital-sync
    # env_file:
    #   - stack.env
    environment:
      PRIMARY_HOST_BASE_URL: ${PRIMARY_HOST_BASE_URL}
      PRIMARY_HOST_PASSWORD: ${PRIMARY_HOST_PASSWORD}
      SECONDARY_HOST_1_BASE_URL: ${SECONDARY_HOST_1_BASE_URL}
      SECONDARY_HOST_1_PASSWORD: ${SECONDARY_HOST_1_PASSWORD}
      INTERVAL_MINUTES: 30
      VERBOSE: 'true'
